### PR TITLE
initial release

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by travi** [comment]
@gr2m any improvements that you would suggest before i promote this to a stable v1?

**Comment by gr2m** [comment]
checking it out now :)

**Comment by gr2m** [comment]
Works like a charm! Here is the code I used to test:

```js
const { Octokit } = require("@octokit/core");
const { createNetrcAuth } = require("octokit-auth-netrc");

const OctokitWithNetrcAuth = Octokit.defaults({
  authStrategy: createNetrcAuth,
});

const octokit = new OctokitWithNetrcAuth();

octokit.request("GET /user").then(console.log).catch(console.log);
```

I'll have a look at the code now

**Comment by gr2m** [comment]
Code looks great :shipit:

**Comment by travi** [comment]
Thanks for taking a look. I should have included my message from slack here too since this change was still passing existing integration tests: https://github.com/travi/github-scaffolder/commit/f23194d3f291e2acc97f42622c5b2eca03d6ff82

**Pull request merged**
